# 开始工作
start:
 # 每天什么时候开始工作呢？
 time: '06:00:25'
 # 打个招呼吧
 text: '一年之计在于春，一日之计在于晨，可莉开始工作啦，各位早安~'
 # 配个图片吧
 img: '早安.gif'

# 结束工作
end:
 time: '01:00:25'
 text: '身体是革命的本钱，工作了这么久了，可莉下班啦，各位晚安，好梦哦~'
 img: '晚安.gif'