#example模块
example:
  'fishCalendar':
    priority: 5000
    rule:
      'news':
        reg: '^#?摸鱼日历$'
        regKey: ''
        dsc: '展示今天的摸鱼日历'
        chatType: 'all'
        event: 'message'
        isShowLog: true
        permission: 'all'
        permissionLevel: 0
        favorabilityLevel: 0