#Wiki模块
Wiki:
  'inquireWiki':
    priority: 5000
    rule:
      'ysWiki':
        reg: '^#?原神*'
        regKey: ''
        dsc: '查询原神BWiki界面'
        chatType: 'all'
        event: 'message'
        isShowLog: true
        permission: 'all'
        permissionLevel: 0
        favorabilityLevel: 0